CREATE TABLESPACE TABLE_db_rizky
DATAFILE 'D:\002. MATERI KULIAH\001. KULIAH\004. SEMESTER 4\BASIS DATA\TUGAS\UTS\data5.dbf'
size 30M;

CREATE USER db_rizky
IDENTIFIED BY 1
DEFAULT TABLESPACE TABLE_db_rizky
QUOTA 30M ON TABLE_db_rizky;

GRANT ALL PRIVILEGES TO db_rizky;

CONN db_rizky/1


create table PENGAJAR 
(
   ID_PENGAJAR          VARCHAR2(20 CHAR),
   NAMA_PENGAJAR        VARCHAR2(50 CHAR),
   TANGGAL_LAHIR        VARCHAR2(20 CHAR),
   ALAMAT_PENGAJAR      VARCHAR2(100 CHAR),
   TELP_PENGAJAR        VARCHAR2(20 CHAR),
   constraint PK_PENGAJAR primary key (ID_PENGAJAR)
);

create table MURID
(
   ID_MURID             VARCHAR2(20 CHAR),
   NAMA                 VARCHAR2(50 CHAR),
   ID_PENGAJAR          VARCHAR2(20 CHAR),
   TANGGAL_LAHIR        VARCHAR2(20 CHAR) ,
   ALAMAT_PENGAJAR      VARCHAR2(100 CHAR),
   TELP_PENGAJAR        VARCHAR2(20 CHAR),
   constraint PK_MURID primary key (ID_MURID),
   constraint FK_MURID_ID_PENGAJAR foreign key (ID_PENGAJAR) references PENGAJAR (ID_PENGAJAR)
);

CREATE VIEW daftar_pengajar AS SELECT * FROM PENGAJAR ORDER BY id_pengajar ASC;

CREATE VIEW table_murid AS SELECT * FROM MURID ORDER BY id_pengajar ASC;


DROP TABLE TABEL_MURID;

ALTER TABLE TABEL_MURID
MODIFY ID_PENGAJAR VARCHAR2(20 char) NOT NULL;

id varchar2(20 char) not nul